### ISSUE TITLE
Profiling any exe for investigation.

### ISSUE THREAD

**Issue by rjobling** [BartmanAbyss/vscode-amiga-debug#102]
I sometimes use the profiler to see how other games/demos are using the blitter and copper.

I do that by running the profiler on my own project as usual and then F12-ing into Winuae where I boot into the game/demo. From there If it succeeds I can sometimes capture a profile and see some of what's going on. Normally I can see the blitter activity and what the copper is up to.

Would it be possible to build functionality into the profiler so it can more effectively be used in this way?

It'd be great if I could run it using any exe and the assembly window would reflect the code that's being executed.

It'd also be great to configure resources in real-time so I can enter addresses and dimensions for bitmaps as I figure out what the code it doing.

**Comment by BartmanAbyss** [comment]
This is actually supported since a few releases, but I guess I hadn't documented it good enough.
Here's a quick rundown
- Start your own WinUAE
- Start your game/demo
- At the point you would like to profile, hit F12 and go to Host>Miscellaneous and hit the 'Save state...' button.
- You can then select the .uss file you just saved from WinUAE in VS Code and hit the "Play" button to run it in the special WinUAE version and hit the profile buttons like you would with your own project.

**Comment by rjobling** [comment]
Tested this and it works great thanks!
