### ISSUE TITLE
Replace exe2adf with amitools

### ISSUE THREAD

**Issue by lw64** [BartmanAbyss/vscode-amiga-debug#135]
The "amitools" suite (https://github.com/cnvogelg/amitools) is compared to "exe2adf" open source. It would be good to use it instead of exe2adf.

**Comment by BartmanAbyss** [comment]
yeah, but it requires python :(

**Comment by lw64** [comment]
At least for Linux/Mac os it would be no problem. And I don't think it is too much a barrier for people to install python.

**Comment by lw64** [comment]
I guess it is a problem on Windows. I don't use it so... :)

**Comment by lw64** [comment]
I also would like to have meson instead of GNU Make as the buildsystem. It is so much more modern and enables lots of other interesting features. But it also depends on Python.

**Comment by BartmanAbyss** [comment]
I understand. But it is the goal to keep everything simple so everyone can start using it without a steep learning curve.

**Comment by lw64** [comment]
Well. Makefiles are much harder to read.

**Comment by BartmanAbyss** [comment]
Sure. But most folks won't even have to touch the makefile. Ofcourse you're free to use whatever build tool you like. The template project is more of a minimal effort thing to get started.

**Comment by lw64** [comment]
I see. Would it be possible to have multiple templates?

**Comment by eli-schwartz** [comment]
Please note in the Meson FAQ: https://mesonbuild.com/FAQ.html#but-i-really-want-a-version-of-meson-that-doesnt-use-python

You can use muon, a c99 reimplementation of Meson (Meson is designed so that reimplementing it in another language should not be an undue burden). Muon publishes prebuilt amd64 binaries, it is 4.5mb statically linked with all dependencies, and 0.5mb dynamically linked.

Yes, you need to depend on ***something***, but it's not as heavyweight as Python. Furthermore, you currently depend on GNU make, and how do you know that's installed?
