### ISSUE TITLE
V1.7.0 does not fire up WinUAE/infinite loop

### ISSUE THREAD

**Issue by ReneKriest** [BartmanAbyss/vscode-amiga-debug#211]
V1.7.0 starts debugging after I hit F5 but is kept busy in an infinite loop without firing up WinUAE.

I reverted to 1.6.9, which works just fine.

No error message in the terminal from V1.7.0, so there is no real hint. (Sorry)

**Comment by BartmanAbyss** [comment]
Hi, any more clues? I did test with the template project and everything worked as it always did. Do you see `winuae-gdb.exe` in your Windows task manager?

**Comment by quadrupedal** [comment]
Can confirm the same issue here. On pressing F5 winuae-gdb.exe does not appear in the task manager, but vscode appears to be waiting for it, with the debug tab open but nothing shown. Ctrl+F5 gives similar results minus the empty debugger.

I can start winuae with the generated config file from the command line, but vscode doesn't connect to it, so that's my workaround for the moment, just building and running with no debugger.

**Comment by BartmanAbyss** [comment]
Can you reproduce it with a clean new project after `Amiga: Init Project`?

**Comment by BartmanAbyss** [comment]
Can reproduce on a different PC. Will investigate. Sorry for the inconvenience.

**Comment by BartmanAbyss** [comment]
tracked down to https://github.com/BartmanAbyss/vscode-amiga-debug/pull/209#discussion_r1102934010_

**Comment by quadrupedal** [comment]
> tracked down to [#209 (comment)](https://github.com/BartmanAbyss/vscode-amiga-debug/pull/209#discussion_r1102934010)_

Which means that adding "emuargs": [] to each configuration in launch.json gives an easy work around. Nice.

**Comment by BartmanAbyss** [comment]
fixed in 1.7.1
